// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"
)

type Accounts struct {
	ID       int32   `json:"id"`
	UserName string  `json:"user_name"`
	Balance  float32 `json:"balance"`
}

type Transfer struct {
	ID         int32     `json:"id"`
	FromUserID int64     `json:"from_user_id"`
	ToUserID   int64     `json:"to_user_id"`
	Amount     float32   `json:"amount"`
	CreatedAt  time.Time `json:"created_at"`
}
